export const ManualMovementsPage = {
  PURCHASE_ORDER: "purchase_order",
  COLLECT_ORDER: "collect_order",
  SALE_ORDER: "sale_order",
  PRODUCTION_ORDER: "production_order",
  PRODUCTION_MAP: "production_map",
  ISSUE_INVOICE: "issue_invoice",
  LAUNCH_FACTORY: "launch_factory",
  CNAB_SHIPPING: "cnab_shipping",
  CONTROL_CHECK: "control_check",
  CONTROL_BANKING: "control_banking",
  ACCOUNTS_PAYABLE: "accounts_payable",
  ACCOUNTS_RECEIVABLE: "accounts_receivable",
  ROMANEIO_SALE: "romaneio_sale",
};
