export const ManualMovementsPage = {
  PURCHASE_ORDER: "/pedido_compra",
  COLLECT_ORDER: "/pedido_compra_recebimento",
  SALE_ORDER: "/pedido_venda",
  ROMANEIO_SALE: "/pedido_venda_romaneio",
  PRODUCTION_ORDER: "/ordem_producao",
  PRODUCTION_MAP: "/mapa_producao",
  ACCOUNTS_RECEIVABLE: "/financeiro_contas_a_receber",
  ACCOUNTS_PAYABLE: "/financeiro_contas_a_pagar",
  CONTROL_CHECK: "/financeiro_controle_cheques",
  CONTROL_BANKING: "/financeiro_controle_bancario",
  CNAB_SHIPPING: "/financeiro_lancamentos_bancarios_cnab",
  LAUNCH_FACTORY: "/troca_de_titulos-factory",
  ISSUE_INVOICE: "/emissao_nota_fiscal_eletronica",
};
